const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const labels = {career:'การงาน',money:'การเงิน',investment:'การลงทุน'};
let focus = 'career', horizon = 'life', toastTimer;
function todayISO(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return ['year','month','day'].map(k=>p.find(v=>v.type===k).value).join('-')}
let asOf=todayISO(), selectedAge=40;
function readURL(){const q=new URLSearchParams(location.search);if(labels[q.get('focus')])focus=q.get('focus');if(horizons[q.get('horizon')])horizon=q.get('horizon');const age=q.get('age');if(age!==null&&/^\d+$/.test(age)&&Number(age)<=108)selectedAge=Number(age);const date=q.get('date');if(date&&/^\d{4}-\d{2}-\d{2}$/.test(date)&&!Number.isNaN(Date.parse(date)))asOf=date;$('#as-of').value=asOf}
function saveURL(){const url=new URL(location.href);url.searchParams.set('focus',focus);url.searchParams.set('horizon',horizon);url.searchParams.set('date',asOf);url.searchParams.set('age',selectedAge);history.pushState(null,'',url)}
function formatDate(date){return new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'))}
function periodText(){const d=formatDate(asOf);if(horizon==='today')return 'วันอ้างอิง: '+d+' · กรุงเทพฯ · ยังไม่คำนวณดาวจร';if(horizon==='year')return 'ช่วงอ้างอิง: '+formatDate(asOf.slice(0,4)+'-01-01')+' – '+formatDate(asOf.slice(0,4)+'-12-31');if(horizon==='quarter'){const end=new Date(asOf+'T12:00:00Z');end.setUTCDate(end.getUTCDate()+89);return 'ช่วงอ้างอิง 90 วัน: '+d+' – '+formatDate(end.toISOString().slice(0,10))}return 'อ้างอิง ณ '+d+' · ต้องยืนยันวันเกิดก่อนระบุช่วง'+(horizon==='life'?'ชีวิต 108 ปี':'บทชีวิต')}
function announceReading(){$('#reading-update').textContent='แสดง '+horizons[horizon].label+' เรื่อง'+labels[focus];$('#period-label').textContent=periodText()}
const horizons = {
 life:{label:'01 / ภาพชีวิต 108 ปี',title:'อยากให้ชีวิตระยะยาว<br>สร้างอะไรไว้ให้ตัวเอง',summary:'เริ่มด้วยทิศทางที่มีความหมาย แล้วค่อยวางช่วงชีวิตแต่ละช่วงให้สนับสนุนกัน แผนที่ช่วยตั้งคำถาม ไม่ได้กำหนดว่าชีวิตต้องเป็นแบบเดียว',question:'อะไรสำคัญ แม้บทบาทของคุณจะเปลี่ยนไป',evidence:'แผนที่ทักษาครบวงรอบและช่วงชีวิตที่เลือก โดยไม่ใช้ปีตัวอย่างแทนปีจริง',footnote:'108 ปีคือกรอบการอ่านวงรอบ ไม่ใช่การคาดการณ์อายุขัยหรือรับประกันเหตุการณ์'},
 chapter:{label:'02 / บทชีวิต',title:'บทนี้ของชีวิต<br>ควรให้พื้นที่กับเรื่องใด',summary:'วางสิ่งที่กำลังตัดสินใจไว้ในช่วงชีวิตระยะยาวก่อน แยกสิ่งที่เป็นพื้นฐานออกจากเรื่องที่เกิดขึ้นชั่วคราว',question:'อะไรควรสร้างต่อ และอะไรควรทบทวน',evidence:'วันเริ่มและสิ้นสุดดาวเสวยอายุ/ดาวแทรกของโปรไฟล์นี้',footnote:'บทอ่านจริงต้องอ้างช่วงเวลาที่คำนวณได้ ต้นแบบนี้ไม่มีดาวเสวยอายุส่วนบุคคล'},
 year:{label:'03 / ปีนี้',title:'เลือกหนึ่งเป้าหมาย<br>ที่พาภาพใหญ่ไปข้างหน้า',summary:'ใช้ภาพระยะยาวเป็นกรอบเลือกสิ่งที่ควรให้ความสำคัญในปีนี้ แล้วกำหนดหลักฐานที่จะใช้ทบทวนแผน',question:'ปลายปี คุณอยากเห็นอะไรเปลี่ยนไป',evidence:'ช่วงวันที่ของปีที่เลือกและดาวจรสู่อาทิตย์ตลอดช่วง ไม่ใช่วันตัวอย่างหนึ่งวันแทนทั้งปี',footnote:'ตัวอย่างการวางแผน ยังไม่ใช่ผลวิเคราะห์ปีปัจจุบันของคุณ'},
 quarter:{label:'04 / แผน 90 วัน',title:'ทำภาพไกลให้ใกล้ขึ้น<br>ด้วยแผนที่ทบทวนได้',summary:'เปลี่ยนทิศทางเป็นงานที่มีขอบเขต วางหมุดหมายระยะสั้น แล้วกลับมาดูว่าข้อมูลจริงยังสนับสนุนแผนเดิมหรือไม่',question:'ใน 90 วัน อะไรจะยืนยันว่าคุณเดินมาถูกทาง',evidence:'บริบทบทชีวิต/ปี และข้อมูลดาวจรของหน้าต่าง 90 วันที่ระบุ',footnote:'แผนควรเปลี่ยนได้เมื่อข้อเท็จจริงเปลี่ยน แม้ภาพตีความทางโหราศาสตร์ยังเหมือนเดิม'},
 today:{label:'05 / วันนี้',title:'วันนี้ เลือกหนึ่งก้าว<br>ที่ไม่หลุดจากภาพใหญ่',summary:'แบบฝึกทบทวนรายวัน: เชื่อมสิ่งที่จะทำกับแผนที่ตั้งไว้ และจดสิ่งที่ต้องตรวจสอบก่อนตัดสินใจ',question:'งานเล็กที่สุดที่ขยับเป้าหมายวันนี้คืออะไร',evidence:'วันและเวลาท้องถิ่นของผู้ใช้ พร้อมดาวจรของวันนั้นจริง ฟีเจอร์นี้ยังไม่ได้เชื่อมในต้นแบบ',footnote:'นี่คือแบบฝึกทบทวนวันนี้ ไม่ใช่ daily horoscope — บทอ่านดาวจรรายวันยังต้องพัฒนาและตรวจสอบ'}
};
const focusContent = {
 career:{reflection:'ลองแยกตำแหน่งงานออกจากคุณค่าที่อยากสร้าง ทักษะใดติดตัวไปได้ แม้เปลี่ยนงานหรือเริ่มบทบาทใหม่',action:'เขียนทักษะที่อยากต่อยอด 1 เรื่อง',copy:'ระบุว่าทักษะนี้เชื่อมกับเป้าหมายอย่างไร และจะทดลองฝึกผ่านงานชิ้นไหน'},
 money:{reflection:'ลองระบุว่าเป้าหมายทางการเงินนี้รองรับชีวิตแบบไหน และมีข้อมูลรายรับ ภาระ หรือข้อจำกัดใดที่ยังไม่ชัด',action:'จดเป้าหมายและข้อมูลที่ยังขาด',copy:'เลือกเป้าหมายหนึ่งข้อ แล้วเขียนสิ่งที่ต้องตรวจสอบก่อนจัดทำแผนทางการเงิน'},
 investment:{reflection:'แยกสมมติฐานจากความเชื่อมั่นของตัวเอง มีหลักฐานอะไรสนับสนุน และข้อมูลแบบใดจะทำให้คุณทบทวนมุมมอง',action:'เขียนเหตุผลและเงื่อนไขทบทวน',copy:'จดสิ่งที่เชื่อ หลักฐานที่ต้องหา และเหตุผลที่จะเปลี่ยนใจ ก่อนพิจารณาการตัดสินใจลงทุน'}
};
function notify(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4500)}
function readJournal(){try{return JSON.parse(localStorage.getItem('solar-atlas-prototype-journal')||'[]')}catch{return []}}
function writeJournal(items){try{localStorage.setItem('solar-atlas-prototype-journal',JSON.stringify(items));return true}catch{notify('เบราว์เซอร์ไม่อนุญาตให้บันทึก กรุณาคัดลอกข้อความเก็บไว้');return false}}
function escapeHTML(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderReading(){const h=horizons[horizon],f=focusContent[focus];$('#reading-label').textContent=h.label;$('#reading-title').innerHTML=h.title;$('#reading-summary').textContent=h.summary;$('#reflection-title').textContent=h.question;$('#reflection-copy').textContent=f.reflection;$('#action-title').textContent=f.action;$('#action-copy').textContent=f.copy;$('#evidence-period').textContent=h.evidence;$('#reading-footnote').textContent=h.footnote+(focus==='investment'?' ใช้ข้อมูลธุรกิจ ราคา และความเสี่ยงจริงประกอบเสมอ ไม่ใช้ดวงเป็นสัญญาณซื้อขาย':'');$$('[data-horizon]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.horizon===horizon)));$$('[data-focus]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.focus===focus)));$('.life-ribbon').hidden=horizon!=='life';$('.ribbon-caption').hidden=horizon!=='life';$('#year-explorer').hidden=horizon!=='life';renderAge();}
function renderJournal(){const items=readJournal();$('#journal-items').innerHTML=items.length?items.map((i,n)=>`<article class="journal-item ${i.done?'done':''}"><span class="eyebrow">${escapeHTML(i.context)}</span><h3>${escapeHTML(i.title)}</h3><p>${escapeHTML(i.copy)}</p><div class="item-actions"><button class="button outline" data-done="${n}">${i.done?'กลับมาทบทวน':'ทำแล้ว / ทบทวนแล้ว'}</button><button class="text-link" data-remove="${n}">ลบบันทึกตัวอย่าง</button></div></article>`).join(''):'<div class="empty-journal"><p class="eyebrow">A PLACE FOR YOUR NEXT STEP</p><h2>เริ่มจากหนึ่งก้าวก็พอ</h2><p>เลือก “เพิ่มในสมุดแผน” จากบทอ่านตัวอย่าง<br>แล้วกลับมาลองทำเครื่องหมายเมื่อทบทวนแล้ว</p></div>';}
function navigate(){let route=location.hash.slice(1)||'home';if(route==='method'){showPage('home');$('#method').scrollIntoView({behavior:'auto'});return}if(!['home','atlas','connections','journal'].includes(route))route='home';showPage(route);window.scrollTo(0,0);if(route==='journal')renderJournal();$('#main').focus({preventScroll:true})}
function showPage(route){$$('.page').forEach(el=>el.hidden=el.id!==route);$$('.header nav a').forEach(a=>{if(a.hash==='#'+route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')})}
window.addEventListener('hashchange',navigate);
window.addEventListener('popstate',()=>{readURL();renderReading();announceReading();navigate()});
$$('[data-intent]').forEach(a=>a.addEventListener('click',()=>{focus=a.dataset.intent;saveURL();renderReading();announceReading()}));
$$('[data-focus]').forEach(b=>b.addEventListener('click',()=>{focus=b.dataset.focus;saveURL();renderReading();announceReading()}));
$$('[data-horizon]').forEach(b=>b.addEventListener('click',()=>{horizon=b.dataset.horizon;saveURL();renderReading();announceReading()}));
$('#as-of').addEventListener('change',e=>{if(e.target.value){asOf=e.target.value;saveURL();announceReading()}});
$('#back-today').addEventListener('click',()=>{asOf=todayISO();horizon='today';$('#as-of').value=asOf;saveURL();renderReading();announceReading()});
$('#save-plan').addEventListener('click',()=>{const f=focusContent[focus],context=contextLabel(),items=readJournal();if(items.some(i=>i.title===f.action&&i.context===context)){notify('แผนนี้อยู่ในสมุดแผนแล้ว');return}if(writeJournal([...items,{title:f.action,copy:f.copy,context,done:false}]))notify('เพิ่มแล้ว · เปิด “สมุดแผน” เพื่อทบทวนได้')});
$('#journal-items').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const items=readJournal();if(b.dataset.done!==undefined)items[Number(b.dataset.done)].done=!items[Number(b.dataset.done)].done;if(b.dataset.remove!==undefined){const index=Number(b.dataset.remove),removed=items.splice(index,1)[0];if(writeJournal(items)){renderJournal();notify('ลบบันทึกตัวอย่างแล้ว');clearTimeout(toastTimer);const undo=document.createElement('button');undo.textContent='ย้อนคืน';undo.addEventListener('click',()=>{const current=readJournal();current.splice(Math.min(index,current.length),0,removed);if(writeJournal(current)){renderJournal();notify('คืนบันทึกแล้ว')}});$('#toast').append(undo);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),20000)}return}if(writeJournal(items))renderJournal()});
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
$('#profile-open').addEventListener('click',()=>$('#profile-dialog').showModal());
$('#unknown-time').addEventListener('change',e=>{$('#birth-time').disabled=e.target.checked;$('#birth-time').required=!e.target.checked});
$('#profile-form').addEventListener('submit',e=>{e.preventDefault();const unknown=$('#unknown-time').checked;$('#profile-dialog').close();$('#profile-form').reset();$('#birth-time').disabled=false;$('#birth-time').required=true;info('ขั้นตอนถัดไป: ยืนยันข้อมูล','<p class="profile-complete">ระบบจริงจะแสดงสรุปข้อมูลเกิดให้ตรวจทานก่อนคำนวณ '+(unknown?'และเว้นลัคนา/เรือนชะตาที่ต้องใช้เวลาเกิด':'พร้อมเมือง เขตเวลา และเวลาที่ใช้คำนวณ')+'</p><p>การสาธิตจบที่ขั้นนี้ ข้อมูลที่กรอกไม่ได้ถูกบันทึกหรือส่งออก และหน้าบทอ่านยังเป็นตัวอย่างเดิม</p>')});
function info(title,html){$('#info-title').textContent=title;$('#info-body').innerHTML=html;$('#info-dialog').showModal()}
$('#bazi-open').addEventListener('click',()=>info('ปาจื่อ: อีกมุมมองหนึ่ง','<p>เสนอให้เป็นชั้นข้อมูลเสริมที่เลือกเปิดได้ หลังอ่านแกนอาทิตย์และภาพใหญ่แล้ว</p><ul><li>แสดงหลักที่ใช้และข้อมูลที่คำนวณแยกจากโหราศาสตร์สากล</li><li>หากตีความต่างกัน ให้เห็นทั้งสองมุมโดยไม่รวมเป็นคะแนนเดียว</li><li>ควรให้ผู้เชี่ยวชาญปาจื่อทบทวนก่อนใช้ประกอบคำแนะนำจริง</li></ul><p>ต้นแบบนี้ยังไม่มีผลปาจื่อส่วนบุคคล</p>'));
const connectionInfo={couple:['คำถามสำหรับคู่ครอง','แต่ละคนต้องการพื้นที่ส่วนตัวและเวลาร่วมกันแบบไหน','เมื่อแผนไม่ตรงกัน เราจะคุยกันอย่างไร','เป้าหมายระยะยาวข้อใดควรตกลงร่วมกัน'],partner:['คำถามสำหรับหุ้นส่วน','ใครรับผิดชอบและตัดสินใจเรื่องใด','ความเห็นต่างและความเสี่ยงจะจัดการอย่างไร','ข้อตกลงใดควรเขียนให้ชัดก่อนเริ่มงาน'],company:['ข้อมูลสำหรับบริษัท','เลือกเหตุการณ์ตั้งต้น: จดทะเบียน เปิดกิจการ หรือเหตุการณ์อื่น พร้อมเหตุผล','ระบุวัน เวลา สถานที่ และเอกสารอ้างอิง ถ้าไม่มีเวลาอย่าสมมติขึ้น','แยกดวงองค์กรออกจากข้อมูลธุรกิจ งบการเงิน และมูลค่าหุ้น']};
$$('[data-connection]').forEach(b=>b.addEventListener('click',()=>{const a=connectionInfo[b.dataset.connection];info(a[0],'<p>คำถามทั่วไปสำหรับเตรียมข้อมูล ไม่ใช่ผลวิเคราะห์ความสัมพันธ์</p><ul>'+a.slice(1).map(t=>'<li>'+t+'</li>').join('')+'</ul>')}));
$('#question-open').addEventListener('click',()=>{$('#question-context').textContent='บริบทตัวอย่าง: '+contextLabel();$('#question-dialog').showModal()});
$('#question-form').addEventListener('submit',e=>{e.preventDefault();const question=$('#question').value.trim();if(!question){$('#question').focus();return}if(writeJournal([...readJournal(),{context:'ร่างคำถาม · '+contextLabel(),title:question,copy:'ยังไม่ได้ส่งให้ AI · เก็บไว้ทบทวนบนเครื่องนี้',done:false}])){$('#question-dialog').close();$('#question-form').reset();notify('เก็บร่างคำถามแล้ว · ยังไม่ได้ส่งให้ AI')}});
function contextLabel(){return horizons[horizon].label+' · '+labels[focus]+(horizon==='life'?' · '+$('#age-output').textContent:'')+' · '+formatDate(asOf)}
function renderAge(){const label='อายุ '+selectedAge+' ปี';$('#age-slider').value=selectedAge;$('#age-slider').setAttribute('aria-valuetext',label);$('#age-direct').value=selectedAge;$('#age-output').textContent=label;$('#age-detail').textContent='กำลังสำรวจ'+label+' · ระบบจริงจะแสดงดาวเสวยอายุ ดาวแทรก และมุมสัมพันธ์สู่อาทิตย์ของปีที่เลือก';$('#age-prev').disabled=selectedAge===0;$('#age-next').disabled=selectedAge===108;}
function setAge(value,commit=true){const n=Number(value);if(value===''||!Number.isInteger(n)||n<0||n>108){renderAge();return}selectedAge=n;renderAge();if(commit)saveURL();}
$('#age-slider').addEventListener('input',e=>setAge(e.target.value,false));$('#age-slider').addEventListener('change',()=>saveURL());$('#age-direct').addEventListener('input',e=>{const v=e.target.value;if(v!==''&&Number.isInteger(Number(v))&&Number(v)>=0&&Number(v)<=108)setAge(v,false)});$('#age-direct').addEventListener('change',e=>setAge(e.target.value));$('#age-prev').addEventListener('click',()=>setAge(selectedAge-1));$('#age-next').addEventListener('click',()=>setAge(selectedAge+1));
readURL();renderReading();announceReading();navigate();
